### ISSUE TITLE
request to fork from dguzek/Simply-Love-SM5

### ISSUE THREAD

**Issue by quietly-turning** [jordando/Simply-Love-Tweaks#1]
This seems like an interesting project that has a lot of energy and interest in shaking up the status quo.  Thank you for working on it.

I think I am interested in reviewing, testing, and building on some of the ideas and work done here, and bringing it into mainline Simply Love in some fashion for a future release.  

It is difficult for me to track what you've changed in the theme code as this repository currently stands.  I could certainly create a new branch at https://github.com/dguzek/Simply-Love-SM5, apply this repository wholsesale, and try to go from there, but that would attribute your work to me, and I'd like you to retain [authorship](https://github.com/dguzek/Simply-Love-SM5/graphs/contributors) for your efforts.

I'm wondering if you are interested in working on this project with the idea that it would eventually lead to a pull request back to mainline Simply Love.  This would be more work on your part and progress would go more slowly.  There would be more angles to consider and things to test for it to be part of a formal release.  There's no obligation to do anything, though the screenshots shown at ZIv suggest there is a lot of potential here that would likely benefit the post-ITG community at large.

I am wondering if you can:

 1. fork https://github.com/dguzek/Simply-Love-SM5 to https://github.com/jordando/Simply-Love-SM5
 2. create a new branch on your fork
 3. apply the changes you've already worked on to that branch

Just getting to that point would help me track and review what code you've changed, and the hope is that we could discuss where to go from there.

Let me know what you think.  Again, thanks for all this.

**Comment by jordando** [comment]
Sure, i can fork/branch tonight. I'd also be interested in working on the project to fit better with mainline Simply Love. I didn't bother testing/working on things I wouldn't personally use but if it provides a benefit to the community at large i wouldn't mind doing so.

**Comment by quietly-turning** [comment]
Thanks for this.  I see it now, over at https://github.com/jordando/Simply-Love-SM5/tree/CustomSongWheel

I briefly looked at the commit diffs, which quickly helped me see that you'd added over 7000 new lines of code.  I'm impressed, humbled, and terrified.  It's going to take me a long time to wrap my head around it all.

**Comment by jordando** [comment]
I think it probably won't be that bad. My original intent was to rebuild
the normal ITG mode except with your casual mode songwheel so I could do
things like tagging/filtering. Along the way I decided I liked a lot of the
UI decisions you made with casual mode and wanted to keep them so I just
copied what I liked and smashed it into a new screen since i could figure
out how to do that more easily than loading actors and modifying from
there. So a large part of the code is just recycled pieces from
screenselectmusic and screenselectmusicCasual.

To be honest it's probably still mostly all your work
